export const ODCZYT_REJESTRU = 'ODCZYT_REJESTRU'
export const ZMIANA_REJESTRU_WYJSCIA = 'ZMIANA_REJESTRU_WYJSCIA'
export const ZMIANA_REJESTRU_WYSATEL = 'ZMIANA_REJESTRU_WYSATEL'
export const ZMIANA_REJESTRU_WYTEMP = 'ZMIANA_REJESTRU_WYTEMP'
export const ZMIANA_REJESTRU_WYTEMPNAST = 'ZMIANA_REJESTRU_WYTEMPNAST'

export const ODCZYT_USTAWIEN = 'ODCZYT_USTAWIEN'
export const ZMIANA_USTAWIEN = 'ZMIANA_USTAWIEN'